-- Core layer: star schema. Dimensions use GENERATED BY DEFAULT so we can insert
-- explicit -1 "Unknown" members.

CREATE TABLE IF NOT EXISTS core.dim_date (
    date_key         INTEGER PRIMARY KEY,          -- YYYYMMDD
    full_date        DATE NOT NULL UNIQUE,
    year             SMALLINT NOT NULL,
    quarter          SMALLINT NOT NULL,
    month            SMALLINT NOT NULL,
    month_name       TEXT NOT NULL,
    iso_week         SMALLINT NOT NULL,
    day_of_month     SMALLINT NOT NULL,
    day_of_week      SMALLINT NOT NULL,            -- ISO: 1 = Monday ... 7 = Sunday
    day_name         TEXT NOT NULL,
    is_weekend       BOOLEAN NOT NULL,             -- Saturday or Sunday
    is_disrupted_day BOOLEAN NOT NULL DEFAULT FALSE,
    disruption_note  TEXT
);

CREATE TABLE IF NOT EXISTS core.dim_airport (
    airport_key    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    icao_code      TEXT NOT NULL UNIQUE,
    iata_code      TEXT,
    airport_name   TEXT NOT NULL,
    municipality   TEXT,
    iso_country    TEXT,
    airport_type   TEXT,
    latitude_deg   DOUBLE PRECISION,
    longitude_deg  DOUBLE PRECISION
);

INSERT INTO core.dim_airport (airport_key, icao_code, airport_name)
VALUES (-1, 'UNKNOWN', 'Unknown airport')
ON CONFLICT (icao_code) DO NOTHING;

CREATE TABLE IF NOT EXISTS core.dim_aircraft (
    aircraft_key           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    icao24                 TEXT NOT NULL UNIQUE,
    registration           TEXT NOT NULL DEFAULT 'Unknown',
    manufacturer           TEXT NOT NULL DEFAULT 'Unknown',
    model                  TEXT NOT NULL DEFAULT 'Unknown',
    typecode               TEXT NOT NULL DEFAULT 'Unknown',
    operator_icao          TEXT NOT NULL DEFAULT 'Unknown',
    is_matched_in_registry BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS core.dim_route (
    route_key        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    origin_icao      TEXT NOT NULL,
    destination_icao TEXT NOT NULL,
    route_label      TEXT NOT NULL,
    UNIQUE (origin_icao, destination_icao)
);

INSERT INTO core.dim_route (route_key, origin_icao, destination_icao, route_label)
VALUES (-1, 'UNKNOWN', 'UNKNOWN', 'Unknown route')
ON CONFLICT (origin_icao, destination_icao) DO NOTHING;

CREATE TABLE IF NOT EXISTS core.fact_flight (
    flight_key                 BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    icao24                     TEXT NOT NULL,
    first_seen_utc             TIMESTAMPTZ NOT NULL,
    last_seen_utc              TIMESTAMPTZ NOT NULL,
    date_key                   INTEGER NOT NULL REFERENCES core.dim_date (date_key),
    aircraft_key               INTEGER NOT NULL REFERENCES core.dim_aircraft (aircraft_key),
    origin_airport_key         INTEGER NOT NULL REFERENCES core.dim_airport (airport_key),
    destination_airport_key    INTEGER NOT NULL REFERENCES core.dim_airport (airport_key),
    route_key                  INTEGER NOT NULL REFERENCES core.dim_route (route_key),
    callsign                   TEXT NOT NULL,
    observed_duration_min      NUMERIC(8, 2) NOT NULL CHECK (observed_duration_min >= 0),
    first_seen_hour_gst        SMALLINT NOT NULL CHECK (first_seen_hour_gst BETWEEN 0 AND 23),
    is_origin_known            BOOLEAN NOT NULL,
    is_destination_known       BOOLEAN NOT NULL,
    is_same_origin_destination BOOLEAN NOT NULL,
    run_id                     BIGINT REFERENCES ops.pipeline_run (run_id),
    UNIQUE (icao24, first_seen_utc)
);

CREATE INDEX IF NOT EXISTS ix_fact_flight_date     ON core.fact_flight (date_key);
CREATE INDEX IF NOT EXISTS ix_fact_flight_aircraft ON core.fact_flight (aircraft_key);
CREATE INDEX IF NOT EXISTS ix_fact_flight_route    ON core.fact_flight (route_key);
CREATE INDEX IF NOT EXISTS ix_fact_flight_origin   ON core.fact_flight (origin_airport_key);
CREATE INDEX IF NOT EXISTS ix_fact_flight_dest     ON core.fact_flight (destination_airport_key);

COMMENT ON TABLE core.fact_flight IS
    'Grain: one ADS-B-observed flight (icao24 + first_seen_utc). Durations are observed '
    'first-seen to last-seen intervals, not scheduled or gate-to-gate block times.';
COMMENT ON COLUMN core.fact_flight.first_seen_hour_gst IS
    'Hour of first_seen_utc in Gulf Standard Time (UTC+4, no daylight saving).';